### PR TITLE
feat: reprovision cluster on Talos v1.8.4

### PR DESCRIPTION
**Pull request by onedr0p**
- Hardware Transcoding is busted on Talos v1.9.0
- Ceph is busted with TRIM nonsense on v19

### CODE REVIEW

**Comment by davralin** [comment]
Shouldn't it be enough to just downgrade talos?

**Comment by onedr0p** [comment]
I'm not sure if I can downgrade 1.9.0 to 1.8.x, plus I need to downgrade ceph to fix other issues

**Comment by davralin** [comment]
> I'm not sure if I can downgrade 1.9.0 to 1.8.x

https://www.talos.dev/v1.9/reference/cli/#talosctl-rollback

The one node I tried this against is stuck in NotReady without a responding API however, so need to check it when I get home.

But you got one of them fancy KVM's, so maybe you'll have better luck than I have! :1st_place_medal: 



> plus I need to downgrade ceph to fix other unrelated issues

image

**Comment by davralin** [comment]
Woop, It just got back up - so it was as easy as rollback - took some time though.

**Comment by davralin** [comment]
image

That's the problem.

````
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
````

That solved it for me.

I'm running on optiplex'es.

**Comment by onedr0p** [comment]
I was able to get transcoding working on 1.9.0 afterall, turns out I wasn't powercycling the nodes during upgrade, only a kexec 😠

**Pull request closed without merging**
